services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - 1194:1194/udp
    volumes:
      - ./ovpn-data-storage:/etc/openvpn
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.200
    restart: unless-stopped
    

  app0:
    image: viking-vulns #our custom image (can be built with the script)
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.10

  app1:
    image: viking-vulns #our custom image (can be built with the script)
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.11

  app2:
    image: viking-vulns #our custom image (can be built with the script)
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.12

  app3:
    image: viking-vulns #our custom image (can be built with the script)
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.13

  app4:
    image: viking-vulns #our custom image (can be built with the script)
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.14
networks:
  viking-vuln-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.0/24 
