#wip
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - 1194:1194/udp
    volumes:
      - ./ovpn-data-storage:/etc/openvpn
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.200
    restart: unless-stopped
    

  app:
    image: viking-vulns #run docker build script
    networks:
      viking-vuln-network:
        ipv4_address: 192.168.69.10
    ports:
      - 2222:22/tcp

networks:
  viking-vuln-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.0/24 
